# Docker Compose for development with build caching
version: '3.8'

services:
  # Development container with volume mounts for live development
  pihole-analyzer-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      cache_from:
        - golang:1.23-alpine
        - pihole-analyzer:builder-cache
    image: pihole-analyzer:dev
    container_name: pihole-analyzer-dev
    volumes:
      # Mount source code for live development
      - .:/app
      # Mount Go cache for faster builds
      - go-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]  # Keep container running
    environment:
      - GOCACHE=/root/.cache/go-build
      - GOMODCACHE=/go/pkg/mod

  # Production container
  pihole-analyzer-prod:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - golang:1.23-alpine
        - alpine:latest
    image: pihole-analyzer:latest
    container_name: pihole-analyzer-prod
    environment:
      - APP_ENV=production

  # Test runner container
  pihole-analyzer-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: pihole-analyzer:test
    container_name: pihole-analyzer-test
    command: ["./pihole-analyzer-test", "--test"]
    volumes:
      # Mount test results output
      - ./test-results:/app/test-results

volumes:
  go-cache:
    driver: local
  go-build-cache:
    driver: local

networks:
  default:
    driver: bridge
