# docker-compose.api-only.yml - API-only deployment configuration for Phase 5
# Complete SSH removal deployment for production environments

version: '3.8'

services:
  pihole-analyzer-api:
    image: ghcr.io/grammatonic/pihole-analyzer:latest-api-only
    container_name: pihole-analyzer-api-only
    
    # API-only environment configuration
    environment:
      # Pi-hole API Configuration
      PIHOLE_HOST: "${PIHOLE_HOST:-pi.hole}"
      PIHOLE_API_ENABLED: "true"
      PIHOLE_API_PASSWORD: "${PIHOLE_API_PASSWORD}"
      PIHOLE_USE_HTTPS: "${PIHOLE_USE_HTTPS:-false}"
      PIHOLE_API_TIMEOUT: "${PIHOLE_API_TIMEOUT:-30}"
      
      # Force API-only mode
      PIHOLE_MIGRATION_MODE: "api-only"
      
      # Logging Configuration
      LOG_LEVEL: "${LOG_LEVEL:-info}"
      LOG_FORMAT: "${LOG_FORMAT:-json}"
      LOG_ENABLE_COLORS: "false"  # Disabled for container logs
      LOG_ENABLE_EMOJIS: "false"  # Disabled for container logs
      
      # Security
      PIHOLE_VERIFY_SSL: "${PIHOLE_VERIFY_SSL:-true}"
      
      # Analysis Configuration
      ANALYSIS_MAX_CLIENTS: "${ANALYSIS_MAX_CLIENTS:-50}"
      ANALYSIS_ONLINE_ONLY: "${ANALYSIS_ONLINE_ONLY:-false}"
      
      # Container Optimization
      GOMEMLIMIT: "64MiB"
      GOMAXPROCS: "2"
    
    # Resource limits for production deployment
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M
    
    # Health check using built-in validation
    healthcheck:
      test: ["CMD", "/usr/local/bin/pihole-analyzer", "--validate-migration", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Network configuration
    networks:
      - pihole-api-network
    
    # Security context
    read_only: true
    security_opt:
      - no-new-privileges:true
    
    # Restart policy
    restart: unless-stopped
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service,version,environment"
    
    # Labels for container management
    labels:
      - "traefik.enable=false"
      - "com.docker.compose.service=pihole-analyzer-api"
      - "com.pihole-analyzer.variant=api-only"
      - "com.pihole-analyzer.version=${VERSION:-latest}"

  # Optional: Configuration validator service
  config-validator:
    image: ghcr.io/grammatonic/pihole-analyzer:latest-api-only
    container_name: pihole-analyzer-config-validator
    
    environment:
      PIHOLE_HOST: "${PIHOLE_HOST:-pi.hole}"
      PIHOLE_API_PASSWORD: "${PIHOLE_API_PASSWORD}"
      PIHOLE_USE_HTTPS: "${PIHOLE_USE_HTTPS:-false}"
      PIHOLE_MIGRATION_MODE: "api-only"
    
    # One-time validation run
    command: ["--validate-migration", "--exit-after-validation"]
    
    networks:
      - pihole-api-network
    
    # Don't restart - this is a one-time validation
    restart: "no"
    
    # Security context
    read_only: true
    security_opt:
      - no-new-privileges:true
    
    labels:
      - "com.docker.compose.service=config-validator"
      - "com.pihole-analyzer.variant=validator"

  # Optional: Monitoring service for API connectivity
  api-monitor:
    image: ghcr.io/grammatonic/pihole-analyzer:latest-api-only
    container_name: pihole-analyzer-api-monitor
    
    environment:
      PIHOLE_HOST: "${PIHOLE_HOST:-pi.hole}"
      PIHOLE_API_PASSWORD: "${PIHOLE_API_PASSWORD}"
      PIHOLE_USE_HTTPS: "${PIHOLE_USE_HTTPS:-false}"
      PIHOLE_MIGRATION_MODE: "api-only"
      LOG_LEVEL: "warn"  # Only show warnings and errors
    
    # Monitor mode - periodic connectivity checks
    command: ["--monitor-mode", "--interval", "300"]  # Check every 5 minutes
    
    networks:
      - pihole-api-network
    
    restart: unless-stopped
    
    # Resource limits for monitoring
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
        reservations:
          cpus: '0.05'
          memory: 16M
    
    # Security context
    read_only: true
    security_opt:
      - no-new-privileges:true
    
    labels:
      - "com.docker.compose.service=api-monitor"
      - "com.pihole-analyzer.variant=monitor"

networks:
  pihole-api-network:
    driver: bridge
    name: pihole-analyzer-api
    # Network configuration for Pi-hole communication
    ipam:
      config:
        - subnet: 172.30.0.0/24

# Configuration volumes (optional - for persistent config)
volumes:
  analyzer-config:
    name: pihole-analyzer-api-config
    driver: local
