version: '3.8'

services:
<<<<<<< HEAD
  # Production service using published container with API configuration
  pihole-analyzer:
    image: ghcr.io/grammatonic/pihole-analyzer:latest
    container_name: pihole-analyzer
    volumes:
      - ~/.pihole-analyzer:/home/appuser/.pihole-analyzer:ro
      - ./reports:/app/reports
    environment:
      # Pi-hole API Configuration
      PIHOLE_HOST: "${PIHOLE_HOST:-pi.hole}"
      PIHOLE_API_ENABLED: "true"
      PIHOLE_API_PASSWORD: "${PIHOLE_API_PASSWORD}"
      PIHOLE_USE_HTTPS: "${PIHOLE_USE_HTTPS:-false}"
      PIHOLE_API_TIMEOUT: "${PIHOLE_API_TIMEOUT:-30}"
=======
  # Production service using published container with environment variable configuration
  pihole-analyzer:
    image: ghcr.io/grammatonic/pihole-analyzer:latest
    container_name: pihole-analyzer
    environment:
      # Pi-hole API Configuration (Required)
      PIHOLE_HOST: "${PIHOLE_HOST:-pi.hole}"
      PIHOLE_API_PASSWORD: "${PIHOLE_API_PASSWORD}"
      
      # Pi-hole API Configuration (Optional)
      PIHOLE_API_ENABLED: "true"
      PIHOLE_USE_HTTPS: "${PIHOLE_USE_HTTPS:-false}"
      PIHOLE_API_TIMEOUT: "${PIHOLE_API_TIMEOUT:-30}"
      PIHOLE_PORT: "${PIHOLE_PORT:-80}"
      
      # Web Interface Configuration
      WEB_ENABLED: "${WEB_ENABLED:-false}"
      WEB_HOST: "${WEB_HOST:-0.0.0.0}"
      WEB_PORT: "${WEB_PORT:-8080}"
      WEB_DAEMON_MODE: "${WEB_DAEMON_MODE:-false}"
>>>>>>> main
      
      # Logging Configuration
      LOG_LEVEL: "${LOG_LEVEL:-info}"
      LOG_ENABLE_COLORS: "${LOG_ENABLE_COLORS:-true}"
      LOG_ENABLE_EMOJIS: "${LOG_ENABLE_EMOJIS:-true}"
      
<<<<<<< HEAD
      # Security and SSL
      PIHOLE_VERIFY_SSL: "${PIHOLE_VERIFY_SSL:-true}"
      
      # Analysis Configuration
      ANALYSIS_ONLINE_ONLY: "${ANALYSIS_ONLINE_ONLY:-false}"
      
=======
      # Analysis Configuration
      ANALYSIS_ONLINE_ONLY: "${ANALYSIS_ONLINE_ONLY:-false}"
      
      # Metrics Configuration
      METRICS_ENABLED: "${METRICS_ENABLED:-true}"
      METRICS_HOST: "${METRICS_HOST:-0.0.0.0}"
      METRICS_PORT: "${METRICS_PORT:-9090}"
      
>>>>>>> main
      # Container Optimization
      GOMEMLIMIT: "${GOMEMLIMIT:-128MiB}"
      GOMAXPROCS: "${GOMAXPROCS:-2}"
    
<<<<<<< HEAD
=======
    # Optional: Mount configuration file for advanced setups
    volumes:
      - ~/.pihole-analyzer:/home/appuser/.pihole-analyzer:ro  # Optional config file
      - ./reports:/app/reports  # Output directory
    
    # Expose ports when web interface is enabled
    ports:
      - "${WEB_PORT:-8080}:${WEB_PORT:-8080}"      # Web dashboard
      - "${METRICS_PORT:-9090}:${METRICS_PORT:-9090}"  # Metrics endpoint
    
>>>>>>> main
    # Resource limits for production deployment
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M
    
    networks:
      - pihole-net
    restart: unless-stopped

  # Development service with live development environment and API testing
  pihole-analyzer-dev:
    build:
      context: .
      target: development
      args:
        VERSION: dev
        BUILD_TIME: "${BUILD_TIME:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
      cache_from:
        - golang:1.23-alpine
        - alpine:latest
    container_name: pihole-analyzer-dev
    volumes:
      - .:/app/source:ro
      - ~/.pihole-analyzer:/home/appuser/.pihole-analyzer
      - ./reports:/app/reports
      - go-cache:/go/pkg/mod
      - build-cache:/home/appuser/.cache/go-build
    environment:
      # Development Configuration
      DEVELOPMENT: "true"
      GOCACHE: "/home/appuser/.cache/go-build"
      GOMODCACHE: "/go/pkg/mod"
      
      # Pi-hole API Configuration for testing
      PIHOLE_HOST: "${PIHOLE_HOST:-pi.hole}"
      PIHOLE_API_ENABLED: "true"
      PIHOLE_USE_HTTPS: "${PIHOLE_USE_HTTPS:-false}"
      
      # Development Logging
      LOG_LEVEL: "debug"
      LOG_ENABLE_COLORS: "true"
      LOG_ENABLE_EMOJIS: "true"
    working_dir: /app
    networks:
      - pihole-net

  # Test service for CI/CD validation
  pihole-analyzer-test:
    build:
      context: .
      target: development
      cache_from:
        - golang:1.23-alpine
        - alpine:latest
    container_name: pihole-analyzer-test
    volumes:
      - ./testing/fixtures:/app/testing/fixtures:ro
      - ./test-results:/app/test-results
    environment:
      - TEST_MODE=true
    command: ["./pihole-analyzer-test", "--test"]
    networks:
      - pihole-net

networks:
  pihole-net:
    driver: bridge

volumes:
  go-cache:
    driver: local
  build-cache:
    driver: local
