name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 8
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
        
    - name: Get dependencies
      run: |
        go mod download
        go mod verify
      timeout-minutes: 2
        
    - name: Build
      run: go build -v .
      timeout-minutes: 2
      
    - name: Test
      run: |
        echo "Running DNS Analyzer tests..."
        ./omg-usage-analyzer --test
      timeout-minutes: 3
      
    - name: Verify
      run: |
        echo "Verifying application..."
        ./omg-usage-analyzer --help
        ./omg-usage-analyzer --create-config
      timeout-minutes: 1
